LOCAL_PATH := $(call my-dir)

ifeq (TARGET_BOARD_OMAP_CPU,4460)

include $(CLEAR_VARS)
LOCAL_MODULE := libsrv_um_SGX540_120
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/system/vendor/lib/libsrv_um_SGX540_120.so
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so 
LOCAL_MODULE_CLASS := SHARED_LIBRARIES

include $(BUILD_PREBUILT)

endif
